FIX __eq__ not considering default
automl/ConfigSpace pull request #232
Opened 2022-01-31 16:41 UTC by KEggensperger

also include weights for categoricals

2022-02-01 15:26 UTC, mfeurer requested changes

2022-02-01 15:26 UTC, mfeurer commented on test/test_hyperparameters.py
> +        self.assertEqual(c1, other)
Could you please add a check where they are unequal based on weights being present only for one HP?

2022-02-08 08:00 UTC, KEggensperger reviewed
looks good to me, thanks

2022-02-08 08:02 UTC, mfeurer approved these changes

2022-02-08 14:43 UTC, merged